version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    container_name: kibana
    networks:
      - elastic
    #environment:
      #ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      #- elasticsearch.url=http://localhost:9200
    ports:
      - "5601:5601"
    links:
      - elasticsearch

networks:
  elastic:
